# Sample workflow for building and deploying an Astro site to Cpanel
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Deploy Astro site to CPanel

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - name: Astro FTP
       uses: radenpioneer/astro-ftp-deploy@v0.1.1
       with:
         server: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
